# Bonn Fernandez - 42101212

# Milestone 1

## *Importing Libraries*

In [29]:
from datetime import date
import pandas as pd
import numpy as np

## *Importing Raw Data*

In [30]:
df_raw = pd.read_csv("../../data/raw/listings.csv")
#df_raw.head()

---
# **(Milestone 1 ends here the rest is just a testing area for Milestone 2)
---
# Rough work on Milestone 2 (Task 1) 

## *Data Clean-Up*

In [27]:
ls_col = df_raw.columns
## invert drop function to keep the columns we need/want
ls_want = ['name',
           'room_type',
           'price',
           'accommodates',
           'minimum_nights',
           'number_of_reviews',
           'review_scores_rating',
           'review_scores_cleanliness',
           'review_scores_checkin',
           'review_scores_communication',
           'review_scores_location'
          ]
ls_not_want = list(df_raw.drop(columns = ls_want).columns)
df_col = df_raw.drop(columns = ls_not_want) #data frame with wanted columns
set(df_col) == set(ls_want) # boolean test
#df_col

NameError: name 'df_raw' is not defined

In [67]:
## Dealing with missing Data
df_nan = df_col.dropna(axis='rows',how='any').reset_index(drop=True)
type(df_nan['price'][1])

str

In [68]:
# Helpful Links
### https://stackoverflow.com/questions/34165876/trying-to-create-grouped-variable-in-python
### https://stackoverflow.com/questions/47333227/pandas-valueerror-cannot-convert-float-nan-to-integer
### https://stackoverflow.com/questions/13682044/remove-unwanted-parts-from-strings-in-a-column

# Helpful commands maybe

### df_nan[df_nan['review_scores_rating'].isnull() == True] <- Counts NaN
### df_col['accommodates']= pd.to_numeric(df_col['accommodates'],errors='coerce') <- Substitute of .astype function
### df_test['price1'] = df_test['price'].str.split('$').str.get(1) <-- getting rid of a specific string

In [26]:
df_format = df_nan.copy() #use .copy() functions so df_format doesnt overwrite df_nan

## still have to organize the accomodates

labels_acc = ['1','2','3','4','5','6-10','10+']
bins_acc = [1,2,3,4,5,6,10,13]
df_format['accommodates'] = pd.cut(x=df_nan['accommodates'],bins=bins_acc,labels=labels_acc,include_lowest=True)

## maybe segregate the min and max nights
labels_nights = ['day(s)','week(s)','month(s)']
bins_nights = [1,7,30,365]
df_format['minimum_nights'] = pd.cut(x=df_nan['minimum_nights'],bins=bins_nights,labels=labels_nights,include_lowest=True)

## still have to convert the price into an object
labels_price = ['<$100','$100-$199','$200-$299','$300-$399','$400-$500','$500+']
bins_price =[1,100,200,300,400,500,1000]
x = pd.to_numeric(df_nan['price'].str.split('$').str.get(1),errors='coerce') # <---maybe list comprhension this?
df_format['price'] = pd.cut(x=x,bins=bins_price,labels=labels_price,include_lowest=True)

## truncate the review_scores_rating to /10 int instead of /100
df_format['review_scores_rating'] = (df_nan['review_scores_rating']*0.1)//1

#display("this is df_nan",df_nan)
#display("This is df_format",df_format)

NameError: name 'df_nan' is not defined

In [7]:
## rename and rearrange columns
rearrange = [
 'name',
 'room_type',
 'price',
 'minimum_nights',
 'accommodates',
 'number_of_reviews',
 'review_scores_rating',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location']
df = df_format.reindex(columns=rearrange)

rename = {
 'name':'Name',
 'room_type':'Room Type',
 'price':'Price',
 'minimum_nights':'Length of Stay',
 'accommodates':'# of tenants',
 'number_of_reviews':'Total Reviews',
 'review_scores_rating':'Experience Rating',
 'review_scores_cleanliness':'Cleanliness Rating',
 'review_scores_checkin':'Checkin Rating',
 'review_scores_communication':'Communication Rating',
 'review_scores_location':'Location Rating'
}
df = df.rename(columns=rename)
df

,Name,Room Type,Price,Length of Stay,# of tenants,Total Reviews,Experience Rating,Cleanliness Rating,Checkin Rating,Communication Rating,Location Rating
0,D1 - Million Dollar View 2 BR,Entire home/apt,$100-$199,month(s),4,16,9.0,9.0,10.0,9.0,10.0
1,Monthly (or Longer ) Designer One Bedroom Down...,Entire home/apt,<$100,week(s),1,430,9.0,10.0,9.0,10.0,10.0
2,Vancouver's best kept secret,Entire home/apt,$100-$199,week(s),1,88,9.0,10.0,10.0,10.0,10.0
3,EcoLoft Vancouver,Entire home/apt,$100-$199,day(s),3,33,9.0,9.0,10.0,9.0,10.0
4,Close to PNE/Hastings Park and East Village,Entire home/apt,$100-$199,day(s),3,5,9.0,10.0,10.0,10.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...
3456,convenient and safe location near Killarney area,Entire home/apt,<$100,day(s),1,2,8.0,10.0,8.0,8.0,10.0
3457,❤️DT+Parking🌈AmazingView⭐️+Transit+Stadium=ForU,Entire home/apt,$100-$199,day(s),2,1,10.0,10.0,10.0,10.0,10.0
3458,Stunning Gastown Loft in Vancouver Downtown,Entire home/apt,$100-$199,day(s),1,2,10.0,10.0,10.0,10.0,10.0
3459,Central 1 BR suite in the heart of Cambie Village,Entire home/apt,<$100,day(s),2,1,10.0,10.0,10.0,10.0,10.0
3460,Large Townhouse Bedroom close to Airport&Skytrain,Private room,<$100,day(s),1,2,9.0,10.0,10.0,10.0,10.0

In [8]:
# ------------TESTING AREA BELOW ---------------- not part of milestones



type(df_test['minimum_nights'][1])
bruh = df_test['price1']
bruh.min()

NameError: name 'df_test' is not defined

In [140]:
df_test = df_nan

## still have to organize the accomodates
labels = ['1','2','3','4','5','6-10','10+']
bins = [1,2,3,4,5,6,10,13]
df_test['accommodates1'] = pd.cut(x=df_test['accommodates'],bins=bins,labels=labels,include_lowest=True)
df_test


## maybe segregate the min and max nights
labels_nights = ['day(s)','week(s)','month(s)']
bins_nights = [1,7,30,365]
df_test['stay'] = pd.cut(x=df_test['minimum_nights'],bins=bins_nights,labels=labels_nights,include_lowest=True)
df_test

## still have to convert the price into an object
#df_test['price1'] = df_test['price'].str.split('$').str.get(1)
#df_test['price1'] = [price.str.split('$').str.get(1) for price in df_test['price']]
#df_test['price1'] = pd.to_numeric(df_test['price1'])
x1 = pd.to_numeric(df_test['price'].str.split('$').str.get(1),errors='coerce') # <---maybe list comprhension this?
labels_price = ['<$100','$100-$199','$200-$299','$300-$399','$400-$500','$500+']
bins_price =[1,100,200,300,400,500,1000]
df_test['price1'] = pd.cut(x=x1,bins=bins_price,labels=labels_price,include_lowest=True)
df_test['price1'].value_counts()
#type(df_test['price1'][1])

## truncate the review_scores_rating to /10 int instead of /100
df_test['rating'] = (df_test['review_scores_rating']*0.1)//1
df_test

## rename and rearrange columns

,name,room_type,accommodates,price,minimum_nights,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,accommodates1,stay,price1,rating
0,D1 - Million Dollar View 2 BR,Entire home/apt,5,$150.00,90,16,93.0,9.0,10.0,9.0,10.0,4,month(s),$100-$199,9.0
1,Monthly (or Longer ) Designer One Bedroom Down...,Entire home/apt,2,$85.00,30,430,93.0,10.0,9.0,10.0,10.0,1,week(s),<$100,9.0
2,Vancouver's best kept secret,Entire home/apt,2,$145.00,30,88,98.0,10.0,10.0,10.0,10.0,1,week(s),$100-$199,9.0
3,EcoLoft Vancouver,Entire home/apt,4,$140.00,3,33,95.0,9.0,10.0,9.0,10.0,3,day(s),$100-$199,9.0
4,Close to PNE/Hastings Park and East Village,Entire home/apt,4,$195.00,3,5,96.0,10.0,10.0,10.0,10.0,3,day(s),$100-$199,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3456,convenient and safe location near Killarney area,Entire home/apt,2,$58.00,7,2,80.0,10.0,8.0,8.0,10.0,1,day(s),<$100,8.0
3457,❤️DT+Parking🌈AmazingView⭐️+Transit+Stadium=ForU,Entire home/apt,3,$140.00,1,1,100.0,10.0,10.0,10.0,10.0,2,day(s),$100-$199,10.0
3458,Stunning Gastown Loft in Vancouver Downtown,Entire home/apt,2,$117.00,2,2,100.0,10.0,10.0,10.0,10.0,1,day(s),$100-$199,10.0
3459,Central 1 BR suite in the heart of Cambie Village,Entire home/apt,3,$85.00,2,1,100.0,10.0,10.0,10.0,10.0,2,day(s),<$100,10.0
3460,Large Townhouse Bedroom close to Airport&Skytrain,Private room,2,$75.00,1,2,90.0,10.0,10.0,10.0,10.0,1,day(s),<$100,9.0

In [4]:
def load_and_process(path_to_rawdata):
    import pandas as pd
    import numpy as np
    # Method chain 1: load data; Clean data
    df1 = pd.read_csv(path_to_rawdata)
    ls_col = df1.columns
    ls_want = ['name',
               'room_type',
               'price',
               'accommodates',
               'minimum_nights',
               'number_of_reviews',
               'review_scores_rating',
               'review_scores_cleanliness',
               'review_scores_checkin',
               'review_scores_communication',
               'review_scores_location'
              ]
    ls_not_want = list(df1.drop(columns = ls_want).columns) ## invert drop function to keep the columns we need/want
    df1 = df1.drop(columns = ls_not_want).dropna(axis='rows',how='any').reset_index(drop=True) #data frame with wanted columns and dealt missing data

    
    # Method chain 2: Processing Data
    df2 = df1.copy()
    labels_acc = ['1','2','3','4','5','6-10','10+']
    bins_acc = [1,2,3,4,5,6,10,13]
    df2['accommodates'] = pd.cut(x=df1['accommodates'],bins=bins_acc,labels=labels_acc,include_lowest=True)

    ## Convert minimum nights into categories
    labels_nights = ['day(s)','week(s)','month(s)']
    bins_nights = [1,7,30,365]
    df2['minimum_nights'] = pd.cut(x=df1['minimum_nights'],bins=bins_nights,labels=labels_nights,include_lowest=True)

    ## Convert str into float value
    labels_price = ['<$100','$100-$199','$200-$299','$300-$399','$400-$500','$500+']
    bins_price =[1,100,200,300,400,500,1000]
    df2['price'] = pd.to_numeric(df1['price'].str.split('$').str.get(1),errors='coerce') # <---maybe list comprhension this?
    #df2['price'] = pd.cut(x=x,bins=bins_price,labels=labels_price,include_lowest=True)
    
    ## truncate the review_scores_rating to /10 int instead of /100
    df2['review_scores_rating'] = (df1['review_scores_rating']*0.1)
    
    ## Sum up the ratings in a new column
    df2['Overall Rating'] = df2['review_scores_rating'] + df2['review_scores_cleanliness'] + df2['review_scores_checkin']+df2['review_scores_communication']+df2['review_scores_location']
    
    ## Bayesian Rating for weighted scores
    N_max = df2['number_of_reviews'].max()
    NR = N_max*df2['Overall Rating'].mean()
    df2['Bayesian Rating'] = (NR + (df2['number_of_reviews']*df2['Overall Rating']))/(N_max+df2['number_of_reviews'])
    
    ## Wrangling Data
    df3 = df2.copy()
    df = (df3
           .reindex(columns=[              
                         'name',
                         'room_type',
                         'minimum_nights',
                         'price',
                         'accommodates',
                         'number_of_reviews',
                         'review_scores_rating',
                         'review_scores_cleanliness',
                         'review_scores_checkin',
                         'review_scores_communication',
                         'review_scores_location',
                         'Overall Rating',
                         'Bayesian Rating'
                           ]
                      )
           .rename(columns={
                         'name':'Name',
                         'room_type':'Room Type',
                         'price':'Price per Night ($)',
                         'minimum_nights':'Length of Stay',
                         'accommodates':'# of tenants',
                         'number_of_reviews':'Total Reviews',
                         'review_scores_rating':'Experience Rating',
                         'review_scores_cleanliness':'Cleanliness Rating',
                         'review_scores_checkin':'Checkin Rating',
                         'review_scores_communication':'Communication Rating',
                         'review_scores_location':'Location Rating',
                         'Overall Rating':'Overall Rating'
                           }           
                 )
           #.align()
           #.head()
           #.style
           #.set_properties(**{'text-align': 'left'})
           #.set_table_styles([dict(selector = 'th', props=[('text-align', 'center')])])
          )
    
   
        
    return df

In [3]:
load_and_process("../../data/raw/listings.csv")

,Name,Room Type,Length of Stay,Price per Night ($),# of tenants,Total Reviews,Experience Rating,Cleanliness Rating,Checkin Rating,Communication Rating,Location Rating,Overall Rating,Bayesian Rating
0,D1 - Million Dollar View 2 BR,Entire home/apt,90,150.0,4,16,9.3,9.0,10.0,9.0,10.0,47.3,48.383069
1,Monthly (or Longer ) Designer One Bedroom Down...,Entire home/apt,30,85.0,1,430,9.3,10.0,9.0,10.0,10.0,48.3,48.366228
2,Vancouver's best kept secret,Entire home/apt,30,145.0,1,88,9.8,10.0,10.0,10.0,10.0,49.8,48.572428
3,EcoLoft Vancouver,Entire home/apt,3,140.0,3,33,9.5,9.0,10.0,9.0,10.0,47.5,48.366073
4,Close to PNE/Hastings Park and East Village,Entire home/apt,3,195.0,3,5,9.6,10.0,10.0,10.0,10.0,49.6,48.418172
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3456,convenient and safe location near Killarney area,Entire home/apt,7,58.0,1,2,8.0,10.0,8.0,8.0,10.0,44.0,48.395965
3457,❤️DT+Parking🌈AmazingView⭐️+Transit+Stadium=ForU,Entire home/apt,1,140.0,2,1,10.0,10.0,10.0,10.0,10.0,50.0,48.411645
3458,Stunning Gastown Loft in Vancouver Downtown,Entire home/apt,2,117.0,1,2,10.0,10.0,10.0,10.0,10.0,50.0,48.414037
3459,Central 1 BR suite in the heart of Cambie Village,Entire home/apt,2,85.0,2,1,10.0,10.0,10.0,10.0,10.0,50.0,48.411645
3460,Large Townhouse Bedroom close to Airport&Skytrain,Private room,1,75.0,1,2,9.0,10.0,10.0,10.0,10.0,49.0,48.411025

In [2]:
def load_and_process(path_to_rawdata):
    import pandas as pd
    import numpy as np
    # Method chain 1: Load Data; Wrangle Columns; Clean Data
    df1 =pd.read_csv(path_to_rawdata)
    df1 = (df1
          .loc[:,['name','room_type','price','accommodates','minimum_nights','number_of_reviews','review_scores_rating','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location']]         
          .dropna(axis='rows',how='any')
          .reset_index(drop=True)
          )

    # Method chain 2: Lets Process the Data! 
    labels_acc = ['1','2','3','4','5','6-10','10+']
    bins_acc = [1,2,3,4,5,6,10,13]
    N_max = df1['number_of_reviews'].max()
    df1 = (df1
           .assign(tenants=lambda x: pd.cut(x.accommodates,bins=bins_acc,labels=labels_acc,include_lowest=True))
           .assign(Price=lambda x: pd.to_numeric(df1['price'].str.split('$').str.get(1),errors='coerce'))
           .assign(Experience_Rating=lambda x: df1['review_scores_rating']*0.1)
           .assign(Overall_Rating=lambda x: (df1['review_scores_rating']*0.1) + df1['review_scores_cleanliness'] + df1['review_scores_checkin']+df1['review_scores_communication']+df1['review_scores_location'])
           .drop(columns=['accommodates','price','review_scores_rating'])
          )
    df2 = df1.assign(Bayesian_Rating=lambda x: ((N_max*df1['Overall_Rating'].mean()) + (df1['number_of_reviews']*df1['Overall_Rating']))/(N_max+df1['number_of_reviews']))

    # Method Chain 3: Rearrange and Rename all the columns
    df = (df2
           .reindex(columns=[              
                         'name',
                         'room_type',
                         'minimum_nights',
                         'Price',
                         'tenants',
                         'number_of_reviews',
                         'Experience_Rating',
                         'review_scores_cleanliness',
                         'review_scores_checkin',
                         'review_scores_communication',
                         'review_scores_location',
                         'Overall_Rating',
                         'Bayesian_Rating'
                           ]
                      )
           .rename(columns={
                         'name':'Name',
                         'room_type':'Room Type',
                         'Price':'Price per Night ($)',
                         'minimum_nights':'Length of Stay',
                         'tenants':'# of tenants',
                         'number_of_reviews':'Total Reviews',
                         'Experience_Rating':'Experience Rating',
                         'review_scores_cleanliness':'Cleanliness Rating',
                         'review_scores_checkin':'Checkin Rating',
                         'review_scores_communication':'Communication Rating',
                         'review_scores_location':'Location Rating',
                         'Overall_Rating':'Overall Rating',
                         'Bayesian_Rating':'Bayesian Rating'
                           }           
                  )   
            )

    return(df)

In [ ]:
'''
def load_and_process(path_to_rawdata):
    import pandas as pd
    import numpy as np
    # Method chain 1: load data; truncating column; deal with missing data
    df1 = pd.read_csv(path_to_rawdata)
    ls_col = df1.columns
    ls_want = ['name',
               'room_type',
               'price',
               'accommodates',
               'minimum_nights',
               'number_of_reviews',
               'review_scores_rating',
               'review_scores_cleanliness',
               'review_scores_checkin',
               'review_scores_communication',
               'review_scores_location'
              ]
    ls_not_want = list(df1.drop(columns = ls_want).columns) ## invert drop function to keep the columns we need/want
    df1 = df1.drop(columns = ls_not_want).dropna(axis='rows',how='any').reset_index(drop=True) #data frame with wanted columns and dealt missing data

    
    # Method chain 2: Reformatting column values
    df2 = df1.copy()
    
    labels_acc = ['1','2','3','4','5','6-10','10+']
    bins_acc = [1,2,3,4,5,6,10,13]
    df2['accommodates'] = pd.cut(x=df1['accommodates'],bins=bins_acc,labels=labels_acc,include_lowest=True)

    ## maybe segregate the min and max nights
    #labels_nights = ['day(s)','week(s)','month(s)']
    #bins_nights = [1,7,30,365]
    #df2['minimum_nights'] = pd.cut(x=df1['minimum_nights'],bins=bins_nights,labels=labels_nights,include_lowest=True)

    ## still have to convert the price into an object
    labels_price = ['<$100','$100-$199','$200-$299','$300-$399','$400-$500','$500+']
    bins_price =[1,100,200,300,400,500,1000]
    df2['price'] = pd.to_numeric(df1['price'].str.split('$').str.get(1),errors='coerce') 
    
    ## truncate the review_scores_rating to /10 int instead of /100
    df2['review_scores_rating'] = (df1['review_scores_rating']*0.1)
    
    ## Sum up the ratings in a new column
    df2['Overall Rating'] = (
        df2['review_scores_rating']+
        df2['review_scores_cleanliness']+
        df2['review_scores_checkin']+
        df2['review_scores_communication']+
        df2['review_scores_location'])
    
    ## Perform Bayesian Rating
    N_max = df2['number_of_reviews'].max()
    NR = N_max*df2['Overall Rating'].mean()
    df2['Bayesian Rating'] = (NR + (df2['number_of_reviews']*df2['Overall Rating']))/(N_max+df2['number_of_reviews'])
    
    ## Method chain 3: Formatting column idices and dataframe
    df3 = df2.copy()
    df = (df3
           .reindex(columns=[              
                         'name',
                         'room_type',
                         'minimum_nights',
                         'price',
                         'accommodates',
                         'number_of_reviews',
                         'review_scores_rating',
                         'review_scores_cleanliness',
                         'review_scores_checkin',
                         'review_scores_communication',
                         'review_scores_location',
                         'Overall Rating',
                         'Bayesian Rating'
                           ]
                      )
           .rename(columns={
                         'name':'Name',
                         'room_type':'Room Type',
                         'price':'Price per Night ($)',
                         'minimum_nights':'Days of Stay',
                         'accommodates':'# of tenants',
                         'number_of_reviews':'Total Reviews',
                         'review_scores_rating':'Experience Rating',
                         'review_scores_cleanliness':'Cleanliness Rating',
                         'review_scores_checkin':'Checkin Rating',
                         'review_scores_communication':'Communication Rating',
                         'review_scores_location':'Location Rating',
                         'Overall Rating':'Overall Rating'}           
                 )
                     )
        
    return df
'''